spring.application.name=requirements-assistant

gemini.api-key=AIzaSyBLcop8sWpDbTWV813EPOj8XqtyWTuuciM
gemini.model=gemini-2.5-flash

spring.datasource.url=jdbc:postgresql://localhost:5433/requirements_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

ai.provider=gemini

# Desabilitar auto-configuração do OpenAI e Ollama (não estamos usando)
spring.ai.openai.enabled=false
spring.ai.openai.speech.enabled=false
spring.ai.openai.audio.speech.enabled=false
spring.ai.ollama.enabled=false

pgvector.host=localhost
pgvector.port=5433
pgvector.database=requirements_db
pgvector.user=postgres
pgvector.password=postgres

auth.jwt.secret=v0dTdqZRvY7bLhDice6HD1ni/MuHSTv6EeAxGGNdbq8=
auth.jwt.issuer=requirements-assistant-api
auth.jwt.ttl-seconds=3600

auth.google.client-id="1003799692856-9t2c1upm3v7acqdlbvif1u7lad8hlsjn.apps.googleusercontent.com"

auth.admin.emails="thallesvasconcelos5@gmail.com"
